# Generated by Django 3.2.14 on 2022-09-19 10:44

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('explanation', models.TextField(default='')),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], max_length=1)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('U', 'uncleaned_marker'), ('W', 'waiting_marker'), ('C', 'cleanup_marker')], default='W', max_length=1)),
                ('cleanup_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_user', to=settings.AUTH_USER_MODEL)),
                ('posted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gave_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gave_user', to=settings.AUTH_USER_MODEL)),
                ('received_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarkerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, max_length=300, null=True, upload_to=api.models.date_upload_to)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.marker')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reward'),
        ),
        migrations.AddField(
            model_name='marker',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
