# Generated by Django 3.2.14 on 2022-09-19 13:59

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('D', 'Deny'), ('C', 'Confirm')], default='W', max_length=1)),
                ('explanation', models.TextField(default='')),
                ('cleanup_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='marker',
            name='cleanup_user',
        ),
        migrations.CreateModel(
            name='ClearImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, max_length=300, null=True, upload_to=api.models.date_upload_to)),
                ('clear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.clear')),
            ],
        ),
        migrations.AddField(
            model_name='clear',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='api.marker'),
        ),
    ]
