# Generated by Django 3.2.14 on 2022-08-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220728_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('C', 'cleanup_marker'), ('W', 'waiting_marker')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='marker',
            name='sizes',
        ),
        migrations.AddField(
            model_name='marker',
            name='sizes',
            field=models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
