# Generated by Django 3.2.14 on 2022-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220818_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('C', 'cleanup_marker'), ('W', 'waiting_marker')], default='W', max_length=1),
        ),
    ]
