# Generated by Django 3.2.14 on 2022-09-01 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20220818_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('C', 'cleanup_marker'), ('W', 'waiting_marker')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='reward',
            name='received_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
