# Generated by Django 3.2.14 on 2022-09-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220901_0410'),
        ('api', '0007_alter_reward_gave_user'),
    ]

    operations = [
    ]
