# Generated by Django 3.2.14 on 2022-09-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_marker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('U', 'uncleaned_marker'), ('W', 'waiting_marker'), ('C', 'cleanup_marker')], default='W', max_length=1),
        ),
    ]
