# Generated by Django 3.2.14 on 2022-09-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_marker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='status',
            field=models.CharField(choices=[('U', 'uncleaned_marker'), ('W', 'waiting_marker'), ('C', 'cleanup_marker')], default='U', max_length=1),
        ),
    ]
